# Generated by Django 4.2.7 on 2025-11-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_analysis.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity_score', models.FloatField()),
                ('relevance_score', models.FloatField()),
                ('sentiment', models.CharField(max_length=20)),
                ('empathy_score', models.FloatField()),
                ('accuracy_score', models.FloatField()),
                ('completeness_score', models.FloatField()),
                ('response_time_avg', models.FloatField()),
                ('resolution_score', models.FloatField()),
                ('escalation_needed', models.BooleanField(default=False)),
                ('fallback_count', models.IntegerField(default=0)),
                ('overall_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='chat_analysis.conversation')),
            ],
        ),
    ]
